version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "4444:4444"
    environment:
        - NODE_ENV=production
        - DB_HOST=db
        - DB_PORT=5432
        - DB_USERNAME=root
        - DB_PASSWORD=user
        - DB_DATABASE=markdown-notes
    depends_on:
        - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: expense-tracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: